### PR TITLE
fix(POCRE-276): Remove Juries from Litigation details page

### PR DESCRIPTION
**Pull request by ericvale0128**
Commented out useless code block to show juries in litigation details page

### CODE REVIEW

**Review by AltiMario — COMMENTED** [review]
please add a screenshot. It will save time for testing

**Comment by ericvale0128** [comment]
image
No juries listed.

**Review by AltiMario — CHANGES_REQUESTED** [review]
This is not the required fix (it is just commenting code).
#276 is about to remove the jury members details wrongly displayed (they have to be hidden) . 
The requirement is to remove the list (not the full function that inform about the process started) AND add an information for the user like "X jury members have been selected for your litigation"

**Comment by ericvale0128** [comment]
@AltiMario Displayed Litigation detail like this.

image

**Review by AltiMario — APPROVED** [review]
Perfect

**Pull request merged**
