### PR TITLE
fix(POCRE-303): Wallet selection based on env

### PR DESCRIPTION
**Pull request by ericvale0128**
Wallet selection based on Env and wallet address format.
In prod, wallet address doesn't start with "addr_test"

### CODE REVIEW

**Review by AltiMario — APPROVED** [review]

**Review by AltiMario — CHANGES_REQUESTED** [review]
"Cannot login with this wallet!" is not an appropriate error message.
When the environment is set for **production**, the message has to be "Wallets connected to test networks are not allowed".
When the environment is set for **development**, the message has to be "Wallets connected to the main network are not allowed".
I believe you have to change a bit the logic of the flow/check.

**Comment by ericvale0128** [comment]
Updated wallet selection by getting wallet network and comparing it with the current project environment variable.

**Comment by ericvale0128** [comment]
In the `auth.controller.js`, it only checks those addresses that have been sent via request.
I think we have to block useless wallets in the frontend so that they can't be sent to the backend to be signed it.
Also in the backend, it's impossible to check if the specific wallet is on which net. (`main`, `prod`, `test`, etc)
That's why `env` has to exist in the frontend.

**Comment by ericvale0128** [comment]
> In prod, wallet address doesn't start with "addr_test"
This is a poor-level checking with the address in string format. For the best and accurate verification, we should have the checking layer using the network it is on.
At this point, this can only be done in the frontend, which has the access to the web3 with Cardano network.

**Review by AltiMario — APPROVED** [review]

**Pull request merged**
